/*
   Emulator top structure generated by
     pgpgc2 : ver 0.0, Sep 9 2003
     Toshiyuki Fukushige
     Revised by Tsuyoshi Hamada
*/

//#define DEBUG

#include <stdio.h>
#include <math.h>
#ifndef PGINT
#define PGINT long long int
#endif

#define NMAN 5
#define NACC 56
#define NPOS 20
#define xsize (100.0)
#define mmin (4.8828125e-4)
#define xoffset (xsize/2.0)
#define xscale (pow(2.0,(double)NPOS)/xsize)
#define mscale (pow(2.0,63.95)/mmin)
#define escale (xscale*xscale)
#define foffset (pow(2.0,19.0))
#define fscale (-xscale*xscale*foffset/mscale)

void force_emu(x,m,eps2,a,n)
        double x[][3];
        double m[];
        double eps2;
        double a[][3];
        int n;
{                                                                   
  int i,j,k;                                                          
  long long int sx;
  long long int sy;
  long long int sz;
  int fx_ofst;
  int fy_ofst;
  int fz_ofst;
  int xi;
  int xj;
  int yi;
  int yj;
  int zi;
  int zj;
  int xij;
  int yij;
  int zij;
  int dx;
  int dy;
  int dz;
  int ieps2;
  int x2;
  int y2;
  int z2;
  int ieps2r;
  int x2y2;
  int z2e2;
  int r2;
  int r1;
  int mj;
  int mjr;
  int r3;
  int mf;
  int dxr;
  int dyr;
  int dzr;
  int fx;
  int fy;
  int fz;
  int fxo;
  int fyo;
  int fzo;
  long long int ffx;
  long long int ffy;
  long long int ffz;
  unsigned int dbg_jd[40000];
  unsigned int dbg_id[4];
  unsigned long long int dbg_fo[4];

  fx_ofst = 0x1260;
  fy_ofst = 0x1260;
  fz_ofst = 0x1260;
                                                                    
  for(i=0;i<n;i++){                                               
    //  for(i=0;i<1;i++){

    xi = ((unsigned int) ((x[i][0] + xoffset)*xscale + 0.5)) & 0xfffff ;
    yi = ((unsigned int) ((x[i][1] + xoffset)*xscale + 0.5)) & 0xfffff ;
    zi = ((unsigned int) ((x[i][2] + xoffset)*xscale + 0.5)) & 0xfffff ;

    if(eps2 == 0.0){                                         
      ieps2 = 0;                                                
    }else if(eps2 > 0.0){                                    
      ieps2 = (((int)(pow(2.0,(double)NMAN)*log(eps2*escale)/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      ieps2 = (((int)(pow(2.0,5.0)*log(-eps2*escale)/log(2.0))) & 0xfff) | 0x3000;
    }                                                      

#ifdef DEBUG
    dbg_id[0] = xi;
    dbg_id[1] = yi;
    dbg_id[2] = zi;
    dbg_id[3] = ieps2;
#endif

    sx = 0;
    sy = 0;
    sz = 0;

    for(j=0;j<n;j++){                                             
      xj = ((unsigned int) ((x[j][0] + xoffset ) * xscale + 0.5)) & 0xfffff ;
      yj = ((unsigned int) ((x[j][1] + xoffset ) * xscale + 0.5)) & 0xfffff ;
      zj = ((unsigned int) ((x[j][2] + xoffset ) * xscale + 0.5)) & 0xfffff ;
      if(m[j] == 0.0){                                         
        mj = 0;                                                
      }else if(m[j] > 0.0){                                    
        mj = (((int)(pow(2.0,(double)NMAN)*log(m[j]*mscale)/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        mj = (((int)(pow(2.0,(double)NMAN)*log(-m[j]*mscale)/log(2.0))) & 0xfff) | 0x3000;
      }                                                      

#ifdef DEBUG
      {
	unsigned int jdata[3];
	//	mj=0;
	jdata[0]=jdata[1]=jdata[2]=0;
	jdata[0] = ((0xfffff & xj)<<0)  | ((0xfff   & yj)<<20);   // lower part of jdata
	jdata[1] = ((0xff    & (yj>>12)) | ((0xfffff & zj)<<8) | (0xf&mj)<<28);  // higer part of jdata
	jdata[2] = 0x7ff&(mj>>4);
	printf("%d 0x%08X %08X %08X\n",j,jdata[2],jdata[1],jdata[0]);
	dbg_jd[3*j+0] = jdata[0];
	dbg_jd[3*j+1] = jdata[1];
	dbg_jd[3*j+2] = jdata[2];
      }
#endif


      //      if(mj != 0x16bf) {fprintf(stderr,"errrrr 0x%x\n",mj);exit(0);}//hoge

      pg_fix_sub_20(xi,xj,&xij);
      pg_fix_sub_20(yi,yj,&yij);
      pg_fix_sub_20(zi,zj,&zij);
      pg_conv_ftol_fix20_log14_man5(xij,&dx);
      pg_conv_ftol_fix20_log14_man5(yij,&dy);
      pg_conv_ftol_fix20_log14_man5(zij,&dz);
      pg_pdelay_14_np8(dx,&dxr);
      pg_pdelay_14_np8(dy,&dyr);
      pg_pdelay_14_np8(dz,&dzr);
      pg_log_shift_log14_1(dx,&x2);
      pg_log_shift_log14_1(dy,&y2);
      pg_log_shift_log14_1(dz,&z2);
      pg_pdelay_14_np5(ieps2,&ieps2r);
      pg_log_unsigned_add_log14_man5(x2,y2,&x2y2);
      pg_log_unsigned_add_log14_man5(z2,ieps2r,&z2e2);
      pg_log_unsigned_add_log14_man5(x2y2,z2e2,&r2);
      pg_log_shift_log14_m1(r2,&r1);
      pg_log_mul_14(r2,r1,&r3);
      pg_pdelay_14_np12(mj,&mjr);
      pg_log_div_14(mjr,r3,&mf);
      pg_log_mul_14(mf,dxr,&fx);
      pg_log_mul_14(mf,dyr,&fy);
      pg_log_mul_14(mf,dzr,&fz);
      pg_log_sdiv_14(fx,fx_ofst,&fxo);
      pg_log_sdiv_14(fy,fy_ofst,&fyo);
      pg_log_sdiv_14(fz,fz_ofst,&fzo);
      pg_conv_ltof_log14_man5_fix49(fxo,&ffx);
      pg_conv_ltof_log14_man5_fix49(fyo,&ffy);
      pg_conv_ltof_log14_man5_fix49(fzo,&ffz);
      pg_fix_accum_f49_s56(ffx,&sx);
      pg_fix_accum_f49_s56(ffy,&sy);
      pg_fix_accum_f49_s56(ffz,&sz);
      //      if((j%((int)(n/4)))==((int)(n/4)-1)) fprintf(stderr,"%d %016llx\n",j,sx);
    }                                                                 
    a[i][0] = ((double)(sx<<(64-NACC)))*fscale/pow(2.0,(double)(64-NACC));
    a[i][1] = ((double)(sy<<(64-NACC)))*fscale/pow(2.0,(double)(64-NACC));
    a[i][2] = ((double)(sz<<(64-NACC)))*fscale/pow(2.0,(double)(64-NACC));
    //    fprintf(stderr,"%d %016llx\t",i,sx<<(64-NACC));
    //    fprintf(stderr,"%d %e\n",i,a[i][0]);

#ifdef DEBUG
      dbg_fo[0] = sx;
      dbg_fo[1] = sy;
      dbg_fo[2] = sz;
      if(i==0)
	for(k=0;k<n;k++)
	  printf("j[%d], 0x%08X%08X%08X\n",k,dbg_jd[3*k+2],dbg_jd[3*k+1],dbg_jd[3*k+0]);
      printf("-------(i=%d)\n",i);
      for(k=0;k<4;k++) 
	printf("i[%d][%d] 0x%X\n",i,k,dbg_id[k]);
      for(k=0;k<3;k++)
	printf("f[%d][%d] 0x%llX\n",i,k,dbg_fo[k]);
#endif

  }                                                                   
}                                                                   
